keys:
  - &users
    - &lelisei 0AAFA0446C8016928C872276DC25BABDE40033A1
  - &hosts
    - &saturn age1s0ftlw5jw3uxy7z5pyhmczt2p7tsg67s2fktl9mg3mx7deyqkyvqym849n
    - &pluto age1xuuygra9vg0pxf9p4y0e5kxr478wf8xsdanaculqtk59epu36ghqfgeffr
    - &work-laptop age1tgf8ytnvup5l7lqn7amq3yl7y3ytk9ejqn7yhzyzm4z47t7m7avsn4t4d5

creation_rules:
  # "lelisei" user secrets
  - path_regex: secrets/users/lelisei.yaml$
    key_groups:
    - pgp:
      - *lelisei
      age:
      - *saturn
      - *pluto
      - *work-laptop
