# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [ ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ ];
  boot.extraModulePackages = [ ];

  # https://github.com/NixOS/nixos-hardware/issues/858
  boot.initrd.systemd.tpm2.enable = false;

  # fileSystems = {
  #   "/" = {
  #     device = "/dev/disk/by-uuid/278308f9-a0f6-42d4-aa22-67cd4fb55eda";
  #     fsType = "btrfs";
  #     options = [
  #       "subvol=root"
  #       "compress=zstd"
  #       "noatime"
  #     ];
  #   };

  #   "/boot" = {
  #     device = "/dev/disk/by-uuid/C8C2-1E8F";
  #     fsType = "vfat";
  #     options = [
  #       "fmask=0022"
  #       "dmask=0022"
  #     ];
  #   };

  #   "/home" = {
  #     device = "/dev/disk/by-uuid/278308f9-a0f6-42d4-aa22-67cd4fb55eda";
  #     fsType = "btrfs";
  #     options = [
  #       "subvol=home"
  #       "compress=zstd"
  #       "noatime"
  #     ];
  #   };

  #   "/persist" = {
  #     device = "/dev/disk/by-uuid/278308f9-a0f6-42d4-aa22-67cd4fb55eda";
  #     fsType = "btrfs";
  #     options = [
  #       "subvol=persist"
  #       "compress=zstd"
  #       "noatime"
  #     ];
  #   };

  #   "/nix" = {
  #     device = "/dev/disk/by-uuid/278308f9-a0f6-42d4-aa22-67cd4fb55eda";
  #     fsType = "btrfs";
  #     options = [
  #       "subvol=nix"
  #       "compress=zstd"
  #       "noatime"
  #     ];
  #   };
  # };

  # swapDevices = [ ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlan0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "aarch64-linux";
}
