# Configuration specific to HP laptop's keyboard
device {
    name = at-translated-set-2-keyboard
    kb_layout = ch
    kb_variant = fr
}

# Configuration specific to HP laptop's external mouse
device {
    name = logitech-m510
    sensitivity = 0.4
}

# Configuration specific to HP laptop's touchpad
device {
    name = syna328f:01-06cb:cd50-touchpad
}
